### ISSUE TITLE
feat: create specification for `ai-studio.yaml` file

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#19]
We need to properly formalize the requirements of this file, and create a proper specification to build on it.

After a discussion with @slemeur we need to include a section for targeting the deployment environment (E.g. Kubernetes)

E.g. 
```yaml
application:
  deploy:
    environment: "kubernetes" | "compose"
    resources: 
      - ./yaml/kubernetes
  containers: 
  ....
```
